name: Crypto Alert Bot

on:
  schedule:
    - cron: '0 * * * *' # S'exécute à chaque début d'heure
  workflow_dispatch: # Permet de le lancer manuellement pour tester

jobs:
  run-bot:
    runs-runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install requests
        run: pip install requests
      - name: Run bot
        run: python trading_bot.py
